import { chromium, devices } from '@playwright/test'
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' })
const ctx = await b.newContext({ ...devices['iPhone 14'], browserName: undefined })
await ctx.route('**://stub.supabase.test/**', r => r.fulfill({status:200,contentType:'application/json',body:'[]'}))
const agora = Math.floor(Date.now()/1000)
const payload = Buffer.from(JSON.stringify({sub:'e2e-user-renata',aud:'authenticated',role:'authenticated',exp:agora+9999,iat:agora})).toString('base64url')
const sess = {access_token:`eyJhbGciOiJIUzI1NiJ9.${payload}.x`,refresh_token:'r',expires_in:9999,expires_at:agora+9999,token_type:'bearer',user:{id:'e2e-user-renata',aud:'authenticated',role:'authenticated',email:'r@v.com',app_metadata:{},user_metadata:{},created_at:'2026-01-01T00:00:00Z'}}
await ctx.addInitScript(s=>localStorage.setItem('ventus.auth',JSON.stringify(s)),sess)
const p = await ctx.newPage()
await p.goto('http://localhost:5288/',{waitUntil:'domcontentloaded'})
const hoje = new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date())
const dias=(n)=>{const d=new Date(`${hoje}T12:00:00Z`);d.setUTCDate(d.getUTCDate()-n);return d.toISOString().slice(0,10)}
await p.evaluate(async([d3])=>{const m=await import('/src/data/db.ts');const db=m.getDb();await db.open()
  await db.vendors.put({id:1,name:'Renata',email:null,role:null,phone:null,is_admin:false,is_active:true,monthly_target:null,auth_user_id:'e2e-user-renata',auth_id:'e2e-user-renata',telegram_id:null,telegram_username:null,created_at:null})
  const L=(id,nome,tp,next)=>({id,vendor:'Renata',source:'market_sweep',company_name:nome,company_domain:null,contact_name:'Ana',contact_title:'Log',contact_email:'a@b.com',contact_phone:'(11) 98765-4321',contact_whatsapp:null,contact_linkedin:null,active_channels:null,stage:'1b',status:'active',touchpoints_count:tp,next_touchpoint_date:next,last_touchpoint_date:null,opportunity_id:null,notes:null,archived_at:null,recycle_after:null,created_at:'2026-02-01T12:00:00Z',updated_at:'2026-02-01T12:00:00Z'})
  await db.leads.bulkPut([L(201,'Embalagens Vale',2,d3),L(202,'Distribuidora Norte',1,d3),L(203,'Frigorífico Sul',3,d3),L(204,'Cosmético Bela',0,d3)])
},[dias(3)])
await p.goto('http://localhost:5288/golden',{waitUntil:'domcontentloaded'})
await p.getByRole('button',{name:'Começar a hora'}).click()
await p.waitForSelector('[role=group][aria-label*="Contato"]')
p.on('console', m=>{ if(m.type()==='error') console.log('[err]', m.text().slice(0,200)) })
console.log('historia antes:', await p.evaluate(()=>history.length), p.url())
await p.goBack({waitUntil:'commit'}).catch(e=>console.log('goBack err', e.message.slice(0,80)))
for (let i=0;i<6;i++){
  await p.waitForTimeout(300)
  const d = await p.getByRole('dialog').count()
  const cont = await p.getByRole('button',{name:'Continuar'}).count()
  console.log(i, 'dialogs', d, 'continuar', cont, 'url', p.url(), 'hist', await p.evaluate(()=>history.length))
}
await b.close()
